const MAIN_MODE = {
    MAIN: 'MAIN',
    PROFILE_LIST_VIEW: 'PROFILE_LIST_VIEW',
    DESIGN_LIST_VIEW: 'DESIGN_LIST_VIEW',
    MY_HISTORY_VIEW: 'MY_HISTORY_VIEW',
    MY_HISTORY_EDIT: 'MY_HISTORY_EDIT',
    MANAGE_VIEW: 'MANAGE_VIEW',
    MANAGE_EDIT: 'MANAGE_EDIT',
}
const EDIT_PROFILE_VIEW_MODE = {
    PREVIEW_MODE: 'PREVIEW_MODE',
    EDIT_MODE: 'EDIT_MODE',
    CROP_MODE_BACKGROUND: 'CROP_MODE_BACKGROUND',
    CROP_MODE_PROFILE: 'CROP_MODE_PROFILE',
}

const TEMPLATE_VIEW_MODE = {
    PREVIEW_MODE: 'PREVIEW_MODE',
    LOAD_TEMPLATE_MODE: 'LOAD_TEMPLATE_MODE',
    EDIT_BACKGROUND_MODE: 'EDIT_BACKGROUND_MODE',
    EDIT_PROFILE_MODE: 'EDIT_PROFILE_MODE',
    EDIT_TEXT_MODE: 'EDIT_TEXT_MODE',
}

const SELECT_DESIGN_TYPE_LIST = [
    { btnTitle: "레이아웃 A 선택", designType: "DESIGN_TYPE_A" },
    { btnTitle: "레이아웃 B 선택", designType: "DESIGN_TYPE_B" },
    { btnTitle: "레이아웃 C 선택", designType: "DESIGN_TYPE_C" },
    { btnTitle: "레이아웃 D 선택", designType: "DESIGN_TYPE_D" },
]

const BACKGROUND_TYPE = {
    TYPE_01: 'TYPE_01',
    TYPE_02: 'TYPE_02',
    USER_IMAGE: 'USER_IMAGE'
}
export default { MAIN_MODE, EDIT_PROFILE_VIEW_MODE, TEMPLATE_VIEW_MODE, SELECT_DESIGN_TYPE_LIST, BACKGROUND_TYPE }